spring:
  config:
    activate:
      on-profile: prod

app:
  jwt:
    secure: true
    refresh:
      domain: ${COOKIE_DOMAIN}
      same-site: Lax

logging:
  level:
    com.amazonaws.util.EC2MetadataUtils: ERROR
    com.amazonaws.services.s3: INFO
    com.kakaobase.snsapp.global.security: INFO
    com.kakaobase.snsapp.domain.auth: INFO
    com.kakaobase.snsapp.domain.posts: INFO
    org.springframework.security: INFO
  discord:
    webhook-url: ${DISCORD_ERROR_WEBHOOK_URL}
    config: classpath:logback-spring.xml